config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/:id' => 'users#show'
  resources :events, :only => [:index, :show, :create, :new, :index] do
    resources :attendances, :only => [:create, :destroy]
  end
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances

  scope :upcoming, -> { where('date > ?', Date.today).order('date ASC') }
  scope :past, -> { where('date < ?', Date.today).order('date DESC') }

  validates :name, :date, :description, presence: true

  def self.attend_past(my_id)
    @connection = ActiveRecord::Base.connection
    @connection.exec_query("SELECT events.id, events.name, events.description, events.date
                                      FROM events join attendances ON events.id = attendances.event_id
                                      WHERE attendances.user_id = #{my_id} AND events.date < '#{Date.today}'")
  end

  def self.attend_upcoming(my_id)
    @connection = ActiveRecord::Base.connection
    @connection.exec_query("SELECT events.id, events.name, events.description, events.date
                                      FROM events join attendances ON events.id = attendances.event_id
                                      WHERE attendances.user_id = #{my_id} AND events.date > '#{Date.today}'")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attend = Attendance.new event_id: params[:event_id], user_id: current_user.id
    @attend.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @attend = Event.find(params[:event_id]).attendances.find(params[:id])
    @attend.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create show]

  def index
    @upcoming = Event.upcoming
    @past = Event.past
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @attend = @event.attendances.where(user_id: current_user.id).blank?
    @will = @event.attendances.where(user_id: current_user.id)
    @total = @event.attendances.count
  end

  private

  def event_params
    params.require(:event).permit(:date, :description, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @past_events = Event.attend_past(current_user.id)
    @upcoming_events = Event.attend_upcoming(current_user.id)
    @event = Event.where(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="row my-3">
  <div class="col-6">
  <h2 class="badge bg-success text-light w-100 fs-3">Upcoming Events</h2>
  <% @upcoming.each do |event| %>
  <div class="card my-4">
    <div class="card-body">
      <h5 class="card-title"><%= event.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= event.date %></h6>
      <p class="card-text"><%= truncate(event.description, length: 150, omission: '...') %></p>
      <div class="d-flex flex-row justify-content-between">
        <%= link_to "Read more", event_path(event), class: 'btn btn-danger px-2 py-1' %>
        <% if user_signed_in? %>
          <% if event.attendances.where(user_id:current_user.id).blank? %>
            <%= link_to event_attendances_path(event), method: :create, class: 'btn btn-success px-2 py-1' do %>
              <i class="fas fa-check-circle"></i>
            <% end %>
          <% else %>
            <%= link_to event_attendances_path(event) + "/" + event.attendances.where(user_id:current_user).first.id.to_s, method: 'delete', action: 'delete', class: 'btn btn-danger px-2 py-1' do %>
              <i class="fas fa-times-circle"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
  </div>
  <div class="col-6">
  <h2 class="badge bg-danger text-light w-100 fs-3">Past Events</h2>
  <% @past.each do |event| %>
    <div class="card my-4">
      <div class="card-body">
        <h5 class="card-title"><%= event.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.date %></h6>
        <p class="card-text"><%= truncate(event.description, length: 150, omission: '...') %></p>
        <div class="d-flex flex-row justify-content-between">
          <%= link_to "Read more", event_path(event), class: "btn btn-danger px-2 py-1" %>
          <% if user_signed_in? %>
            <% if event.attendances.where(user_id:current_user.id).blank? %>
              <%= button_to "I didn't attend", '#', class: 'btn btn-danger px-2 py-1', :disabled => true %>
            <% else %>
              <%= button_to 'Attended', '#', class: 'btn btn-success px-2 py-1', :disabled => true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h2 class="badge bg-danger text-light w-100 fs-3 mt-3">Create Event</h2>
<%= form_for :event, url: events_path do |f| %>
  <% if @event.errors.any? %>
    <% @event.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-6">
      <p>
        <h5 class="card-title"><%= f.label :name %></h5>
        <%= f.text_field :name, class: 'form-control' %>
      </p>

      <p>
        <h5 class="card-title"><%= f.label :date %></h5>
        <%= f.date_field :date, class: 'form-control' %>
      </p>
    </div>
    <div class="col-6">
      <p>
        <h5 class="card-title"><%= f.label :description %></h5>
        <%= f.text_area :description, class: 'form-control text-area' %>
      </p>
    </div>
  </div>
  <p class="d-flex justify-content-center">
    <%= f.submit "Save Event", class: 'btn btn-success fw-bold mx-auto w-50' %>
  </p>
<% end %>

app/views/events/show.html.erb
<h2 class="badge bg-danger text-light w-100 fs-3 mt-3"><%= @event.name %></h2>
<div class="row ">
  <div class="col-6 my-4">
    <div class="d-flex justify-content-between align-items-center">
      <h2>Description</h2>
      <% if @attend %>
        <%= link_to event_attendances_path(@event), id: 'attend', method: :post, class: 'btn btn-success px-2 py-1' do %>
          <i class="fas fa-check-circle"></i>
        <% end %>
      <% else %>
        <%= link_to event_attendances_path(@event) + "/" + @event.attendances.where(user_id:current_user).first.id.to_s, id: 'notattend', method: 'delete', action: 'delete', class: 'btn btn-danger px-2 py-1' do %>
          <i class="fas fa-times-circle"></i>
        <% end %>
      <% end %>
    </div>
    <p><%= @event.description %></p>
    <div class="d-flex justify-content-between align-items-center">
      <h2>When?</h2>
      <h3 class="text-danger fw-bold"> <%= @event.date.strftime("%A, %d %B %Y") %></h3>
    </div>
  </div>
  <div class="col-6 my-4">
    <h2 class="badge bg-success text-light w-100 fs-4">Attenders (<%= @total %>)</h2>
    <% @event.attendances.each do |attenders| %>
      <div class="d-flex justify-content-between position-relative hover px-1 rounded">
        <p class="fw-bold fs-4 my-1">
          <i class="fas fa-angle-double-right text-success me-2"></i>
          <%= attenders.user.username.capitalize %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/413324cf63.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <nav class="navbar navbar-light navbar-expand-lg bg-dark rounded-bottom">
    <div class="container-fluid">
      <%= link_to "Private Events", root_path, class: 'navbar-brand fs-2 text-danger' %>
      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item rounded hover-nav">
            <%= link_to "Create Event", new_event_url, class: "nav-link fs-5 text-light" %>
          </li>
          <li class="nav-item rounded hover-nav">
            <%= link_to "#{current_user.username.capitalize}'s Events", "#{root_url}users/#{current_user.id}", class: "nav-link fs-5 text-light" %>
          </li>
        </ul>
      <% end %>
      <div class="d-flex flex-column justify-content-between">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if !user_signed_in? %>
              <li class="nav-item rounded hover-nav">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link fs-5 text-light"%>
              </li>
              <li class="nav-item rounded hover-nav">
                <%= link_to "Sign Up", new_user_registration_url, class: "nav-link fs-5 text-light"%>
              </li>
              </ul>
            <% else %>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item rounded hover-nav">
                  <%= link_to "Log out", destroy_user_session_path, :method=>'delete', class: "nav-link fs-5 text-light" %>
              </ul>
            <% end %>
            </div>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-6">
    <h2 class="badge bg-danger text-light w-100 fs-3 mt-3">My Created Events</h2>
    <% @event.each do |event| %>
    <div class="card my-4">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= event.date %></h6>
        </div>
        <div class="d-flex flex-row justify-content-between">
          <%= link_to "Read more", event_path(event), class: 'btn btn-danger px-2 py-1' %>
          <% if user_signed_in? %>
            <% if event.attendances.where(user_id:current_user.id).blank? %>
              <%= link_to event_attendances_path(event), method: :create, class: 'btn btn-success px-2 py-1' do %>
                <i class="fas fa-check-circle"></i>
              <% end %>
            <% else %>
              <%= link_to event_attendances_path(event) + "/" + event.attendances.where(user_id:current_user).first.id.to_s, method: 'delete', action: 'delete', class: 'btn btn-danger px-2 py-1' do %>
                <i class="fas fa-times-circle"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="col-6">
    <h2 class="badge bg-success text-light w-100 fs-3 mt-3">My upcoming events</h2>
    <% @upcoming_events.each do |event| %>
      <div class="d-flex justify-content-between position-relative hover px-1">
        <p class="fw-bold fs-4 my-1">
          <i class="fas fa-angle-double-right text-danger me-2"></i>
          <%= link_to event['name'], event_path(event['id']), class: 'stretched-link text-reset text-decoration-none' %>
        </p>
        <p class="fs-4 my-1"><%= event['date']%></p>
      </div>
    <% end %>
    <h2 class="badge bg-danger text-light w-100 fs-3 mt-3">My past events</h2>
    <%@past_events.each do |event| %>
      <div class="d-flex justify-content-between position-relative hover px-1 rounded">
        <p class="fw-bold fs-4 my-1">
          <i class="fas fa-angle-double-right text-danger me-2"></i>
          <%= link_to event['name'], event_path(event['id']), class: 'stretched-link text-reset text-decoration-none' %>
        </p>
        <p class="fs-4 my-1"><%= event['date']%></p>
      </div>
    <% end %>
  </div>
</div>